import 'package:json_annotation/json_annotation.dart';
part 'apple_search_model.g.dart'; // Give this file access to the one generated by JsonSerializable

@JsonSerializable() // Uses the JsonSerializable package to enable easy de-serialization of JSON objects returned from APIs.
class AppleSongAttributes {
  AppleSongAttributes(this.url); // Constructor with only necessary argument.

  String url;

  // Factory method that constructs an AppleSongAttributes instance using a corresponding method generated by JsonSerializable in the '.g' version of this file.
  factory AppleSongAttributes.fromJson(Map<String, dynamic> json) =>
      _$AppleSongAttributesFromJson(json);
}

@JsonSerializable()
class AppleSong {
  AppleSong(this.attributes);

  AppleSongAttributes attributes;

  factory AppleSong.fromJson(Map<String, dynamic> json) =>
      _$AppleSongFromJson(json);
}

@JsonSerializable()
class AppleSongs {
  AppleSongs(this.data);

  List<AppleSong> data;

  factory AppleSongs.fromJson(Map<String, dynamic> json) =>
      _$AppleSongsFromJson(json);
}

@JsonSerializable()
class AppleSearchResult {
  AppleSearchResult(this.songs);

  AppleSongs songs;

  factory AppleSearchResult.fromJson(Map<String, dynamic> json) =>
      _$AppleSearchResultFromJson(json);
}

@JsonSerializable()
class AppleSearch {
  AppleSearch(this.results);

  AppleSearchResult results;

  factory AppleSearch.fromJson(Map<String, dynamic> json) =>
      _$AppleSearchFromJson(json);
}
